services:
  db:
    container_name: fuepucha_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3300:3306'
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    container_name: fuepucha_phpmyadmin
    image: phpmyadmin:latest
    ports:
      - '8085:80'
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpassword
    depends_on:
      - db